// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package ovsmodel

const InterfaceTable = "Interface"

type (
	InterfaceAdminState       = string
	InterfaceCFMRemoteOpstate = string
	InterfaceDuplex           = string
	InterfaceLinkState        = string
)

var (
	InterfaceAdminStateUp         InterfaceAdminState       = "up"
	InterfaceAdminStateDown       InterfaceAdminState       = "down"
	InterfaceCFMRemoteOpstateUp   InterfaceCFMRemoteOpstate = "up"
	InterfaceCFMRemoteOpstateDown InterfaceCFMRemoteOpstate = "down"
	InterfaceDuplexHalf           InterfaceDuplex           = "half"
	InterfaceDuplexFull           InterfaceDuplex           = "full"
	InterfaceLinkStateUp          InterfaceLinkState        = "up"
	InterfaceLinkStateDown        InterfaceLinkState        = "down"
)

// Interface defines an object in Interface table
type Interface struct {
	UUID                      string                     `ovsdb:"_uuid"`
	AdminState                *InterfaceAdminState       `ovsdb:"admin_state" validate:"omitempty,max=9223372036854775806,oneof='up' 'down'"`
	BFD                       map[string]string          `ovsdb:"bfd" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	BFDStatus                 map[string]string          `ovsdb:"bfd_status" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	CFMFault                  *bool                      `ovsdb:"cfm_fault"`
	CFMFaultStatus            []string                   `ovsdb:"cfm_fault_status" validate:"dive,max=9223372036854775806"`
	CFMFlapCount              *int                       `ovsdb:"cfm_flap_count" validate:"omitempty,max=9223372036854775806"`
	CFMHealth                 *int                       `ovsdb:"cfm_health" validate:"omitempty,min=0,max=100"`
	CFMMpid                   *int                       `ovsdb:"cfm_mpid" validate:"omitempty,max=9223372036854775806"`
	CFMRemoteMpids            []int                      `ovsdb:"cfm_remote_mpids" validate:"dive,max=9223372036854775806"`
	CFMRemoteOpstate          *InterfaceCFMRemoteOpstate `ovsdb:"cfm_remote_opstate" validate:"omitempty,max=9223372036854775806,oneof='up' 'down'"`
	Duplex                    *InterfaceDuplex           `ovsdb:"duplex" validate:"omitempty,max=9223372036854775806,oneof='half' 'full'"`
	Error                     *string                    `ovsdb:"error" validate:"omitempty,max=9223372036854775806"`
	ExternalIDs               map[string]string          `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Ifindex                   *int                       `ovsdb:"ifindex" validate:"omitempty,min=0,max=4294967295"`
	IngressPolicingBurst      int                        `ovsdb:"ingress_policing_burst" validate:"min=0,max=9223372036854775806"`
	IngressPolicingKpktsBurst int                        `ovsdb:"ingress_policing_kpkts_burst" validate:"min=0,max=9223372036854775806"`
	IngressPolicingKpktsRate  int                        `ovsdb:"ingress_policing_kpkts_rate" validate:"min=0,max=9223372036854775806"`
	IngressPolicingRate       int                        `ovsdb:"ingress_policing_rate" validate:"min=0,max=9223372036854775806"`
	LACPCurrent               *bool                      `ovsdb:"lacp_current"`
	LinkResets                *int                       `ovsdb:"link_resets" validate:"omitempty,max=9223372036854775806"`
	LinkSpeed                 *int                       `ovsdb:"link_speed" validate:"omitempty,max=9223372036854775806"`
	LinkState                 *InterfaceLinkState        `ovsdb:"link_state" validate:"omitempty,max=9223372036854775806,oneof='up' 'down'"`
	LLDP                      map[string]string          `ovsdb:"lldp" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	MAC                       *string                    `ovsdb:"mac" validate:"omitempty,max=9223372036854775806"`
	MACInUse                  *string                    `ovsdb:"mac_in_use" validate:"omitempty,max=9223372036854775806"`
	MTU                       *int                       `ovsdb:"mtu" validate:"omitempty,max=9223372036854775806"`
	MTURequest                *int                       `ovsdb:"mtu_request" validate:"omitempty,min=1,max=9223372036854775806"`
	Name                      string                     `ovsdb:"name" validate:"max=9223372036854775806"`
	Ofport                    *int                       `ovsdb:"ofport" validate:"omitempty,max=9223372036854775806"`
	OfportRequest             *int                       `ovsdb:"ofport_request" validate:"omitempty,min=1,max=65279"`
	Options                   map[string]string          `ovsdb:"options" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	OtherConfig               map[string]string          `ovsdb:"other_config" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Statistics                map[string]int             `ovsdb:"statistics" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Status                    map[string]string          `ovsdb:"status" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Type                      string                     `ovsdb:"type" validate:"max=9223372036854775806"`
}
