// Code generated by "libovsdb.modelgen"
// DO NOT EDIT.

package ovsmodel

const ManagerTable = "Manager"

type (
	ManagerConnectionMode = string
)

var (
	ManagerConnectionModeInBand    ManagerConnectionMode = "in-band"
	ManagerConnectionModeOutOfBand ManagerConnectionMode = "out-of-band"
)

// Manager defines an object in Manager table
type Manager struct {
	UUID            string                 `ovsdb:"_uuid"`
	ConnectionMode  *ManagerConnectionMode `ovsdb:"connection_mode" validate:"omitempty,max=9223372036854775806,oneof='in-band' 'out-of-band'"`
	ExternalIDs     map[string]string      `ovsdb:"external_ids" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	InactivityProbe *int                   `ovsdb:"inactivity_probe" validate:"omitempty,max=9223372036854775806"`
	IsConnected     bool                   `ovsdb:"is_connected"`
	MaxBackoff      *int                   `ovsdb:"max_backoff" validate:"omitempty,min=1000,max=9223372036854775806"`
	OtherConfig     map[string]string      `ovsdb:"other_config" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Status          map[string]string      `ovsdb:"status" validate:"dive,keys,max=9223372036854775806,endkeys,max=9223372036854775806"`
	Target          string                 `ovsdb:"target" validate:"max=9223372036854775806"`
}
